site_name: kmviz v0.5.0
site_url: https://tlemane.github.io/kmviz

repo_url:  https://github.com/tlemane/kmviz
repo_name: tlemane/kmviz
edit_uri: edit/main/docs/

nav:
  - Home: 'index.md'
  - User Guide:
    - Installation: 'installation.md'
    - Quickstart: 'quickstart.md'
    - Configuration:
      - configuration/index.md
      - Builtins Provider: 'builtins/provider.md'
      - Builtins MetaDB: 'builtins/metadb.md'
    - Interface:
      - interface/index.md
      - Database mode: 'interface/database.md'
      - Session mode: 'interface/session.md'
      - Plot-Only mode: 'interface/plot_only.md'
      - REST API: 'interface/rest.md'
      - User options: 'configuration/user_options.md'
  - Advanced:
    - Plugin:
      - plugins/index.md
      - Provider plugin: 'plugins/plugin_provider.md'
      - MetaDB plugin: 'plugins/plugin_metadb.md'
      - Layout plugin: 'plugins/plugin_layout.md'
      - Instance plugin: 'plugins/plugin_instance.md'
    - Deployment:
      - deploy/index.md
      - Docker: 'deploy/docker.md'
      - Docker compose: 'deploy/compose.md'
      - API: 'deploy/api.md'

plugins:
  - mike
  - search

theme:
    name: material
    highlightjs: true
    palette:
    - media: "(prefers-color-scheme: light)"
      primary: blue
      accent: blue
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode

    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/weather-night
        name: Switch to dark mode

    icon:
      repo: fontawesome/brands/github

    navigation_depth: 3
    features:
      - navigation.tabs
      - navigation.tracking
      - navigation.section
      - navigation.path
      - navigation.expand
      - navigation.footer
      - navigation.indexes
      - content.code.copy
      - content.code.select
      - content.code.annotate
      - search.suggest
      - search.highlight
      - search.share


markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
  - admonition
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.details
  - attr_list
  - toc:
      permalink: true
      toc_depth: 4
  - tables
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

extra_css:
  - stylesheets/extra.css

extra:
  generator: false
  version:
    provider: mike