site_name: kmviz documentation

nav:
  - Home: 'index.md'
  - 'User Guide':
    - 'Installation': 'installation.md'
    - 'Quickstart': 'quickstart.md'
    - 'Configuration': 'configuration.md'
      - 'Builtins': 'builtin.md'
    - 'Interface': 'interface.md'
    - 'Plot-Only mode': 'plot_only.md'
  - 'Advanced':
    - 'Plugin': 'plugin.md'
    - 'Deployment': 'deploy.md'
theme:
    name: material
    highlightjs: true
    palette:
    - scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

    features:
      - navigation.tabs
      - navigation.tracking
      - content.code.copy
      - content.code.select
      - content.code.annotate

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
  - admonition
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - attr_list
  - toc:
      permalink: true
  - tables
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

extra_css:
  - stylesheets/extra.css

extra:
  version:
    provider: mike