site_name: kmviz v0.6.0
site_url: https://tlemane.github.io/kmviz

repo_url:  https://github.com/tlemane/kmviz
repo_name: tlemane/kmviz
edit_uri: edit/main/docs/

nav:
  - Home: 'index.md'
  - Usage:
    - Introduction: 'introduction.md'
    - Interface:
      - Database mode:
        - 'interface/database/index.md'
        - Input: 'interface/database/input.md'
        - Submit: 'interface/database/submit.md'
        - Navigation: 'interface/database/nav.md'
        - Tabs:
          - Index: 'interface/database/index_table.md'
          - Table: 'interface/database/table.md'
          - Figure:
            - 'interface/database/figure/index.md'
            - Map: 'interface/database/map.md'
            - Plot: 'interface/database/plot.md'
          - Sequence: 'interface/database/sequence.md'
      - Session mode: 'interface/session.md'
      - Plot mode: 'interface/plot.md'
    - API:
      - api/index.md
      - Infos: 'api/info.md'
      - Metadata: 'api/metadata.md'
      - Session: 'api/session.md'
  - Advanced:
    - Introduction: 'advanced.md'
    - Installation: 'installation.md'
    - Quickstart: 'quickstart.md'
    - Configuration:
      - configuration/index.md
      - Builtins Provider: 'builtins/provider.md'
      - Builtins MetaDB: 'builtins/metadb.md'
    - CLI:
      - cli/index.md
      - app: 'cli/app.md'
      - api: 'cli/api.md'
      - config: 'cli/config.md'
      - plugin: 'cli/plugin.md'
    - Deployment:
      - deploy/index.md
      - Docker: 'deploy/docker.md'
      - Docker compose: 'deploy/compose.md'
    - Plugin:
      - plugins/index.md
      - Provider plugin: 'plugins/plugin_provider.md'
      - MetaDB plugin: 'plugins/plugin_metadb.md'
      - Layout plugin: 'plugins/plugin_layout.md'
      - Instance plugin: 'plugins/plugin_instance.md'

plugins:
  - mike
  - search
  - termynal

theme:
    name: material
    highlightjs: true
    palette:
    - media: "(prefers-color-scheme: light)"
      primary: blue
      accent: blue
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode

    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/weather-night
        name: Switch to dark mode

    icon:
      repo: fontawesome/brands/github

    navigation_depth: 3
    features:
      - navigation.tabs
      - navigation.tracking
      - navigation.section
      - navigation.path
      - navigation.expand
      - navigation.footer
      - navigation.indexes
      - content.code.copy
      - content.code.select
      - content.code.annotate
      - search.suggest
      - search.highlight
      - search.share
      - content.tabs.link


markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
  - admonition
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - attr_list
  - toc:
      permalink: true
      toc_depth: 4
  - tables
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

extra_css:
  - stylesheets/extra.css

extra:
  generator: false
  version:
    provider: mike