name: kmviz-ci

on:
  push:
    paths: ['kmviz/**', 'tests/kmviz/**', '.github/workflows/ci.yml']

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: 3.x
      - uses: actions/cache@v2
        with:
          key: poetry-1.7.1-0
          path: ~/.local
      - uses: snok/install-poetry@v1
        with:
          version: 1.7.1
          virtualenvs-create: true
          virtualenvs-in-project: true
      - uses: actions/cache@v2
        with:
          path: .venv
          key: pydeps-${{ hashFiles('**/poetry.lock') }}

      - run: poetry install --no-interaction --no-root
        if: steps.cache-deps.outputs.cache-hit != 'true'
      - run: poetry install --no-interaction

      - name: Shutdown Ubuntu MySQL
        run: sudo service mysql stop

      - uses: mirromutth/mysql-action@v1.1
        with:
          mysql version: '8.0'
          mysql database: 'kmviz'
          mysql root password: 'pass'

      - run: sudo mysql --host=127.0.0.1 --user=root --password=pass kmviz < tests/kmviz/metadata/test_sql.sql

      - run: poetry run pytest