name: kmviz-ci

on:
  push:
    paths: ['kmviz/**', 'tests/kmviz/**', '.github/workflows/ci.yml']

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.9", "3.10", "3.11", "3.12"]

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_DATABASE: kmviz
          MYSQL_ROOT_PASSWORD: pass
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - uses: actions/cache@v2
        with:
          key: poetry-1.7.1-0
          path: ~/.local

      - uses: snok/install-poetry@v1
        with:
          version: 1.7.1
          virtualenvs-create: true
          virtualenvs-in-project: true

      - run: pip install pytest
      - run: pip install .
      - run: sudo mysql --host=127.0.0.1 --user=root --password=pass kmviz < tests/kmviz/metadata/test_sql.sql
      - run: poetry run pytest