name: kmviz-doc

on:
  push:
    paths: ['docs/**', '.github/workflows/doc.yml']
    branches: ['main']

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: 3.x
      - uses: actions/cache@v2
        with:
          key: ${{ github.ref }}
          path: .cache
      - run: pip install mkdocs-material mike
      - run: mkdocs gh-deploy -f ./docs/mkdocs.yml --force