name: kmviz-release

on: workflow_dispatch

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: 3.x

      - run: pip install build
      - run: python -m build

      - name: Upload to github release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: 'dist/kmviz-*.tar.gz'
          tag: ${{ github.ref }}
          body: kmviz ${{ github.ref }}
          prerelease: true
